# golangci-lint configuration
# Run: golangci-lint run

version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - copyloopvar
    - whitespace
    - bodyclose
    - noctx
    - gosec
    - errorlint
    - nilerr
    - tparallel

formatters:
  enable:
    - gofmt
    - goimports
