package operators

// Operator contains information about a train operator
type Operator struct {
	Abbr string // Short code like "DB", "SBB", "ÖBB"
	Name string // Full name like "DB Fernverkehr AG"
}

// GetOperator returns the operator for an admin ID
func GetOperator(adminID string) *Operator {
	if op, ok := adminIDToOperator[adminID]; ok {
		return &Operator{Abbr: op[0], Name: op[1]}
	}
	return nil
}

// GetOperatorAbbr returns the abbreviation for an admin ID
func GetOperatorAbbr(adminID string) string {
	if op, ok := adminIDToOperator[adminID]; ok {
		return op[0]
	}
	return ""
}

// GetOperatorName returns the full name for an admin ID
func GetOperatorName(adminID string) string {
	if op, ok := adminIDToOperator[adminID]; ok {
		return op[1]
	}
	return ""
}

// adminIDToOperator maps admin IDs to [abbr, name] pairs
var adminIDToOperator = map[string][2]string{
	"8":      {"S", "S-Bahn Berlin"},
	"19":     {"EST", "EUROSTAR"},
	"51":     {"PKP", "PKP Intercity"},
	"54":     {"CD", "Ceske Drahy"},
	"55":     {"MAV", "MAV"},
	"56":     {"ZSS", "ZSSK"},
	"71":     {"REN", "RENFE"},
	"74":     {"SJ", "SJ"},
	"78":     {"HZ", "HZPP"},
	"79":     {"SZ", "Slovenske zeleznice"},
	"80":     {"DB", "DB Fernverkehr AG"},
	"81":     {"ÖBB", "Österreichische Bundesbahnen"},
	"82":     {"CFL", "CFL"},
	"83":     {"TI", "Trenitalia"},
	"84":     {"NS", "Nederlandse Spoorwegen"},
	"85":     {"SBB", "SBB"},
	"86":     {"DSB", "Dänische Staatsbahnen"},
	"87":     {"SCF", "SNCF"},
	"88":     {"SCB", "SNCB"},
	"3018":   {"THA", "THALYS"},
	"3189":   {"ARV", "ARRIVA vlaky"},
	"3230":   {"VBG", "vogtlandbahn - Die Länderbahn GmbH DLB"},
	"3236":   {"WB", "WESTbahn"},
	"3246":   {"IC", "RegioJet"},
	"3270":   {"TN", "TRENORD"},
	"3288":   {"GW", "GW Train Regio"},
	"3332":   {"KZC", "KZC Doprava s.r.o."},
	"3393":   {"TGV", "SNCF Voyages Deutschland"},
	"3613":   {"StB", "Steiermarkbahn und Bus GmbH"},
	"80001":  {"S", "S-Bahn Berlin"},
	"550043": {"GyS", "GySEV"},
	"743051": {"ST", "Snälltåget"},
	"800151": {"DB", "DB Regio AG Nordost"},
	"800153": {"DB", "DB Regio AG Nordost"},
	"800154": {"DB", "DB Regio AG Nordost"},
	"800155": {"DB", "DB Regio AG Nordost"},
	"800156": {"DB", "DB Regio AG Nordost"},
	"800157": {"DB", "DB Regio AG Nordost"},
	"800158": {"DB", "DB Regio AG Nordost"},
	"800159": {"DB", "DB Regio AG Nordost"},
	"800160": {"DB", "DB Regio AG Nordost"},
	"800161": {"DB", "DB Regio AG Nordost"},
	"800163": {"DB", "DB Regio AG Nordost"},
	"800165": {"DB", "DB Regio AG Nordost"},
	"800166": {"DB", "DB Regio AG Nordost"},
	"800201": {"DB", "DB Regio AG Nord"},
	"800271": {"DB", "DB Regio AG Nord"},
	"800279": {"DB", "DB Regio AG Nord"},
	"800292": {"DB", "DB Regio AG Nord"},
	"800293": {"DB", "DB Regio AG Nord"},
	"800295": {"DB", "DB Regio AG Nord"},
	"800310": {"DB", "DB Regio AG NRW"},
	"800318": {"DB", "DB Arriva"},
	"800333": {"DB", "DB Regio AG NRW"},
	"800337": {"DB", "DB Regio AG NRW"},
	"800338": {"DB", "DB Regio AG NRW"},
	"800348": {"DB", "DB Regio AG NRW"},
	"800349": {"DB", "DB Regio AG NRW"},
	"800351": {"DB", "DB Regio AG NRW"},
	"800352": {"DB", "DB Regio AG NRW"},
	"800354": {"DB", "DB Regio AG NRW"},
	"800363": {"DB", "DB Regio AG NRW"},
	"800413": {"DB", "DB Regio AG Südost"},
	"800417": {"DB", "DB Regio AG Südost"},
	"800430": {"EGB", "DB RegioNetz Verkehrs GmbH Erzgebirgsbahn"},
	"800445": {"DB", "DB Regio AG Südost"},
	"800456": {"DB", "DB Regio AG Südost"},
	"800469": {"DB", "DB Regio AG Südost"},
	"800478": {"DB", "DB Regio AG Südost"},
	"800486": {"DB", "DB Regio AG Südost"},
	"800487": {"DB", "DB Regio AG Südost"},
	"800489": {"DB", "DB Regio AG Südost"},
	"800523": {"KHB", "DB RegioNetz Verkehrs GmbH Kurhessenbahn"},
	"800528": {"S", "DB Regio AG S-Bahn Rhein-Main"},
	"800535": {"DB", "DB Regio AG Mitte"},
	"800553": {"DB", "DB Regio AG Mitte"},
	"800571": {"DB", "DB Regio AG Mitte"},
	"800572": {"DB", "DB Regio AG Mitte"},
	"800574": {"DB", "DB Regio AG Mitte"},
	"800603": {"WFB", "DB RegioNetz Verkehrs GmbH Westfrankenbahn"},
	"800622": {"DB", "DB Regio AG Baden-Württemberg"},
	"800631": {"DB", "DB Regio AG Baden-Württemberg"},
	"800632": {"DB", "DB Regio AG Baden-Württemberg"},
	"800640": {"SWX", "DB Regio AG Mitte SÜWEX"},
	"800643": {"S", "DB Regio AG S-Bahn Stuttgart"},
	"800647": {"DB", "DB Regio AG Baden-Württemberg"},
	"800659": {"DB", "DB Regio AG Baden-Württemberg"},
	"800693": {"DB", "DB Regio AG Baden-Württemberg"},
	"800694": {"DB", "DB Regio AG Baden-Württemberg"},
	"800714": {"DB", "DB Regio AG Bayern"},
	"800720": {"DB", "DB Regio AG Bayern"},
	"800721": {"DB", "DB Regio AG Bayern"},
	"800725": {"S", "DB Regio AG S-Bahn München"},
	"800734": {"DB", "DB Regio AG Bayern"},
	"800742": {"DB", "DB Regio AG Bayern"},
	"800746": {"DB", "DB Regio AG Bayern"},
	"800755": {"DB", "DB Regio AG Bayern"},
	"800759": {"DB", "DB Regio AG Bayern"},
	"800765": {"DB", "DB Regio AG Bayern"},
	"800767": {"DB", "DB Regio AG Bayern"},
	"800772": {"DB", "DB Regio AG Bayern"},
	"800785": {"DB", "DB Regio AG Bayern"},
	"800790": {"DB", "DB Regio AG Bayern"},
	"FLX10":  {"FLX", "FlixTrain"},
	"FLX11":  {"FLX", "FlixTrain"},
	"FLX15":  {"FLX", "FlixTrain"},
	"FLX20":  {"FLX", "FlixTrain"},
	"FLX30":  {"FLX", "FlixTrain"},
	"FLX35":  {"FLX", "FlixTrain"},
	"0S":     {"S", "S-Bahn Hamburg"},
	"A0":     {"AKN", "AKN Eisenbahn GmbH"},
	"A6":     {"AVG", "Albtal-Verkehrs-Gesellschaft mbH"},
	"R1":     {"ME", "metronom"},
	"R2":     {"ERB", "eurobahn"},
	"N1":     {"NWB", "NordWestBahn"},
	"N2":     {"NWB", "NordWestBahn"},
	"W3":     {"WFB", "WestfalenBahn"},
	"GA":     {"GA", "Go-Ahead Baden-Württemberg GmbH"},
	"GY":     {"GA", "Go-Ahead Bayern GmbH"},
	"NX":     {"NX", "National Express"},
	"L8":     {"BRB", "Bayerische Regiobahn"},
	"M8":     {"BRB", "Bayerische Regiobahn"},
	"T8":     {"BRB", "Bayerische Regiobahn"},
	"Y8":     {"BRB", "Bayerische Regiobahn"},
	"A9":     {"ag", "agilis"},
	"S9":     {"ag", "agilis"},
	"X1":     {"erx", "erixx"},
	"X2":     {"erx", "erixx"},
	"EB":     {"RB", "Erfurter Bahn GmbH"},
	"EX":     {"RE", "Erfurter Bahn GmbH"},
	"V6":     {"vlx", "vlexx"},
	"CX":     {"MRB", "Mitteldeutsche Regiobahn"},
	"LD":     {"TL", "trilex - Die Länderbahn GmbH DLB"},
	"RD":     {"VBG", "vogtlandbahn - Die Länderbahn GmbH DLB"},
	"O9":     {"OPB", "oberpfalzbahn - Die Länderbahn GmbH DLB"},
	"W9":     {"WBA", "waldbahn - Die Länderbahn GmbH DLB"},
	"A8N":    {"ALX", "alex - Die Länderbahn GmbH DLB"},
	"AM":     {"ABR", "Abellio Rail Mitteldeutschland GmbH"},
	"AB":     {"ABR", "SWEG Bahn Stuttgart GmbH"},
	"NB":     {"RB", "NEB Niederbarnimer Eisenbahn"},
	"UW":     {"UBB", "Usedomer Bäderbahn"},
	"SB":     {"RB", "Süd-Thüringen-Bahn GmbH"},
	"SBX":    {"RE", "Süd-Thüringen-Bahn GmbH"},
	"HL":     {"HSB", "Harzer Schmalspurbahn"},
	"MW":     {"MBB", "Mecklenburgische Bäderbahn Molli"},
	"BD":     {"SDG", "SDG Sächsische Dampfeisenbahngesellschaft mbH"},
	"R4":     {"VIA", "VIAS Rail GmbH"},
	"TR":     {"RB", "MittelrheinBahn (Trans Regio)"},
	"RS":     {"RE", "Regionalverkehre Start Deutschland GmbH"},
	"K4":     {"HLB", "HLB Hessenbahn GmbH"},
	"N4":     {"RB", "cantus Verkehrsgesellschaft"},
	"CD":     {"CB", "City-Bahn Chemnitz"},
	"H6":     {"HzL", "Hohenzollerische Landesbahn (SWEG)"},
	"H7":     {"HzL", "Hohenzollerische Landesbahn (SWEG)"},
	"R7":     {"HzL", "Hohenzollerische Landesbahn (SWEG)"},
	"N6":     {"SWE", "Südwestdeutsche Landesverkehrs-GmbH"},
	"S6":     {"SWE", "SWEG Südwestdeutsche Landesverkehrs-GmbH"},
	"F7":     {"RB", "Bodensee-Oberschwaben-Bahn"},
	"E0":     {"EVB", "EVB ELBE-WESER GmbH"},
	"R0":     {"ENO", "enno"},
	"BE":     {"BE", "Bentheimer Eisenbahn"},
	"O0":     {"NBE", "Nordbahn Eisenbahngesellschaft"},
	"N0":     {"neg", "Norddeutsche Eisenbahn Gesellschaft"},
	"D3":     {"RTB", "Rurtalbahn"},
	"PB":     {"RB", "Hanseatische Eisenbahn GmbH"},
	"RC":     {"AZS", "AUTOZUG Sylt"},
	"Z8":     {"BZB", "Bayerische Zugspitzbahn"},
}
